21 add endpoint to check sync
swapper-org/NodeChain pull request #22
Opened 2021-10-23 08:10 UTC by swapper-phoenix

# Description

Fixes #21  (issue)

## Dependencies (if any)

- Fix ethereumgo connection bug
- Add endpoint to check synchronization in ETH, BTC and BCH.
- Add BCH constants to make it similar to BTC

## Type of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [x] **This change requires a documentation update**

# How Has This Been Tested?

### ETH SYNC

```sh
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1, "method":"syncing","params":{}}' http://localhost:60001/rpc
{"id": 1, "jsonrpc": "2.0", "result": {"syncing": true, "syncPercentage": "6.905658629231632%", "currentBlockIndex": 755778, "latestBlockIndex": 10944329}}
```

### BTC SYNC
```sh
~$ curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1, "method":"syncing","params":{}}' http://localhost:60001/rpc
{"id": 1, "jsonrpc": "2.0", "result": {"syncing": true, "syncPercentage": "5.732548291803841%", "currentBlockIndex": 352747, "latestBlockIndex": 2101201}}
```

**Test Configuration**:
* Operating system (output of `cat /etc/os-release`):
```sh
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel version (output of `uname -sr`): Linux 4.15.0-143-generic
* Architecture (output of `uname -m`): x86_64

# Related PR or Docs PR

[Docs PR related](https://github.com/swapper-org/NodeChain-docs/pull/1) 
Other PR related # 

# Good practices to consider

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-10-27 17:52 UTC, 0xp3gasus commented
Where is the RPC Endpoint to check sync in BTC?

2021-10-28 16:42 UTC, phoenix-web3 commented
> Where is the RPC Endpoint to check sync in BTC?

Last commit

2021-10-29 00:06 UTC, 0xp3gasus commented on docker-compose/mainnet/eth.yml
> +    command: --http --http.addr=ethereumgo --cache=1024 --http.port=8545 --syncmode=full --gcmode=archive --ws --ws.addr=ethereumgo --ws.port=8546 --ws.origins=connector --http.vhosts=ethereumgo
According to parameter definition: 
`--http.vhosts value                 Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard. (default: "localhost")`

Why did you set ethereumgo as value? Why should not be Connector?

2021-10-29 00:06 UTC, 0xp3gasus commented on docker-compose/testnet/eth.yml
> +    command: --http --http.addr=ethereumgo --ropsten --cache=1024 --http.port=8545 --syncmode=full --gcmode=archive --ws --ws.addr=ethereumgo --ws.port=8546 --ws.origins=connector --http.vhosts=ether
According to parameter definition:
`--http.vhosts value Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard. (default: "localhost")`

Why did you set ethereumgo as value? Why should not be Connector?

2021-10-29 00:09 UTC, 0xp3gasus requested changes
Please, review comments. Thank you

2021-10-29 18:03 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/syncing_response.json
> +"required": [
Use correct tabs

2021-10-29 18:04 UTC, swapper-pegasus commented on Connector/btc/rpcschemas/syncing_response.json
> +"required": [
Use correct tabs

2021-11-03 12:40 UTC, swapper-phoenix commented on Connector/btc/rpcschemas/syncing_response.json
> +"required": [
Resolved in last commit

2021-11-03 12:40 UTC, swapper-phoenix commented on Connector/bch/rpcschemas/syncing_response.json
> +"required": [
Resolved in last commit

2021-11-03 12:41 UTC, swapper-phoenix commented on docker-compose/testnet/eth.yml
> +    command: --http --http.addr=ethereumgo --ropsten --cache=1024 --http.port=8545 --syncmode=full --gcmode=archive --ws --ws.addr=ethereumgo --ws.port=8546 --ws.origins=connector --http.vhosts=ether
As you say and according to definition:
`from which to accept requests`

Ethereumgo is the one who accept requests

2021-11-03 12:41 UTC, swapper-phoenix commented on docker-compose/mainnet/eth.yml
> +    command: --http --http.addr=ethereumgo --cache=1024 --http.port=8545 --syncmode=full --gcmode=archive --ws --ws.addr=ethereumgo --ws.port=8546 --ws.origins=connector --http.vhosts=ethereumgo
As you say and according to definition:
`from which to accept requests`

Ethereumgo is the one who accept requests

2021-11-03 12:42 UTC, swapper-phoenix commented
@swapper-pegasus Should we merge #23 and rebase before merging this PR?

2021-11-03 18:37 UTC, swapper-pegasus commented
> @swapper-pegasus Should we merge #23 and rebase before merging this PR?

Yes, we should merge #23 first, and then merge this pull request with version 1.1.1

2021-11-30 19:00 UTC, swapper-pegasus approved these changes

2021-11-30 19:00 UTC, merged