28 standarize decimal responses
swapper-org/NodeChain pull request #42
Opened 2021-12-07 17:37 UTC by swapper-phoenix

# Description
To standardize all responses that return a decimal number it is proposed to return all such responses in JSON number type.

Due to the poor implementation of the standard number type in languages like Javascript it may cause some problems in the future to return data as Number instead of String.

Fixes #28 (issue)

## Dependencies (if any)

## Type of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **This change requires a documentation update**

# How Has This Been Tested?

- Test A
- Test B

**Test Configuration**:
* Operating system (output of `cat /etc/os-release`):
* Kernel version (output of `uname -sr`):
* Architecture (output of `uname -m`):

# Related PR or Docs PR

Docs PR related # 
Other PR related # 

# Good practices to consider

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-31 09:43 UTC, hippocampusSwapper commented
It would be nice if you could put a PR to reflect these changes also in the customer side package.

Package:  https://github.com/swapper-org/swapper-core/tree/develop/packages/swapper-nodechain-client
Docs: https://hippocampus.gitbook.io/swapper-1/repositorio-monorepo/packages/swapper-nodechain-client

2022-01-02 22:36 UTC, swapper-phoenix commented
> It would be nice if you could put a PR to reflect these changes also in the client side package.
> 
> Package: https://github.com/swapper-org/swapper-core/tree/develop/packages/swapper-nodechain-client Docs: https://hippocampus.gitbook.io/swapper-1/repositorio-monorepo/packages/swapper-nodechain-client

Perfect, i could do that tomorrow

2022-01-04 11:12 UTC, swapper-pegasus commented on Connector/bch/apirpc.py
>      response = {FEE_PER_BYTE: utils.convertToSatoshi(feePerByte[FEE_RATE])}
```utils.convertToSatoshi``` still return a string value

2022-01-04 11:17 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/syncing_response.json
> -            "type": "string"
Why this type change does not have a change in its apirpc method?

2022-01-04 11:17 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/syncing_response.json
> -            "type": "string"
Same as in currentBlock field

2022-01-04 11:23 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/getaddressbalance_response.json
> -                    "type": "string"
```utils.convertToSatoshi``` has not been modified. The function still return a string value

2022-01-04 11:23 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/getaddressbalance_response.json
> +                    "type": "integer"
Same as ```confirmed``` field

2022-01-04 11:24 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/getaddressesbalance_response.json
> -                        "type": "string"
```utils.convertToSatoshi``` has not been modified. The function still return a string value

2022-01-04 11:24 UTC, swapper-pegasus commented on Connector/bch/rpcschemas/getaddressesbalance_response.json
> -                        "type": "string"
Same as ```confirmed``` field

2022-01-04 11:26 UTC, swapper-pegasus commented on Connector/btc/rpcschemas/syncing_response.json
> -            "type": "string"
Why this type change does not have a change in its apirpc method?

2022-01-04 11:26 UTC, swapper-pegasus commented on Connector/btc/rpcschemas/syncing_response.json
> -            "type": "string"
Same as ```currentBlock```field

2022-01-04 11:36 UTC, swapper-pegasus commented on Connector/eth/rpcschemas/syncing_response.json
> -            "type": "string"
Why this type change does not have a change in its apirpc method?

2022-01-04 11:37 UTC, swapper-pegasus commented on Connector/eth/rpcschemas/syncing_response.json
> +            "type": "integer"
Same as ```currentBlock```field

2022-01-04 11:42 UTC, swapper-pegasus requested changes
Please, review comments. Thanks for your contribution 💪🏽

2022-01-04 13:06 UTC, swapper-pegasus approved these changes
Thanks for your contribution.

2022-01-04 13:06 UTC, merged